#!/bin/bash
## Logging functions
INFO(){ echo "INFO: $*";}
WARN(){ echo "WARN: $*";}
ERRO(){ echo "ERRO: $*"; exit 1;}

## Check some deps
bin_exist(){ command -v "$1" &> /dev/null || ERRO "Missing ${1}!"; }
for bin in wine winetricks wineserver winepath wineboot; do
    bin_exist $bin
done

## Define useful functions
rm_w(){ rm -f "$1"; }

## Some vars
export PREFIXCOMMAND TMP BASE_DIR

export WINEPREFIX WINEARCH
export WINE_REQ_MOD=( steam sandbox corefonts )
export INSTALL_PATH
export SANDBOX_FORCE=true
export STEAM_ARGS="-no-cef-sandbox"

CONF=/etc/steam-wine.conf
TMP="$(mktemp -u)"

## Initialization
# shellcheck source=steam-wine.conf
source "$CONF" &> /dev/null || ERRO "Missing: ${CONF}!"

[ -z "$WINEARCH" ]         && WINEARCH=win32
[ -z "$BASE_DIR" ]         && BASE_DIR="$HOME/.local/share/steam-wine"
[ -z "$WINEPREFIX" ]       && WINEPREFIX="$BASE_DIR/WINE.$WINEARCH/"
[ -z "$INSTALL_PATH" ]     && INSTALL_PATH="$BASE_DIR/steam/"

case "$1" in
    steam|wineserver|winetricks|winecfg);;
    *)
        echo "Usage:"
        echo "  steam-wine <args>"
        echo "args:"
        echo "  steam"
        echo "  wineserver <args>"
        echo "  winetricks <args>"
        echo "  winecfg"
        exit 1
    ;;
esac

{
    INFO "Check: Base dir $BASE_DIR"
    mkdir -p "$BASE_DIR"
}

{
    INFO "Check: wineprefix exist $WINEPREFIX"
    if [ ! -d "$WINEPREFIX" ]; then
        INFO "Wine prefix not exist"
        INFO "So try recreate it"
        wineboot &> /dev/null
        INFO "Created: $WINEPREFIX"
    fi
    INFO "Last tested version: wine-2.19"
    INFO "Your version: $(wine --version)"
}

{
    INFO "Check: wineprefix configured"
    cd "$WINEPREFIX" || exit 1
    if [ ! -f "winetricks.log" ]; then
        winetricks -q --optout "${WINE_REQ_MOD[@]}" || ERRO "Something went wrong!"
    fi

    if [ "$SANDBOX_FORCE" == "true" ]; then
            INFO "Check: wine can access only to wine drive C:/ + X:/ (steam)"
            for link in "$WINEPREFIX/dosdevices"/*; do
                [[ "$link" =~ c: ]] && continue # For default link to ../drive_c
                rm -v "$link"
            done
    fi
}

{
    case "$1" in
        wineserver|winetricks|winecfg)
            ARG="$1"; shift; exec "$ARG" "$@"
        ;;
    esac
}

{
    case "$1" in
        steam)
            find -H "$BASE_DIR" -name "Steam.exe" > "$TMP"
            read -r STEAM_PATH < "$TMP"

            if [ ! -f "$STEAM_PATH" ]; then
                ERRO "Can't find installed Steam!"
            fi

            INFO "Initialization Finished"
            $PREFIXCOMMAND wine "$STEAM_PATH" $STEAM_ARGS
        ;;
    esac
}
